image: node:9.4.0

cache:
  paths:
  - node_modules/
  - cache/Cypress
  - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  - cypress-install
  - cypress-e2e

Build:
  stage: build
  tags:
  - node
  before_script:
  - cd todo-app/
  - yarn config set cache-folder .yarn
  - yarn install
  script:
  - yarn build

Test:
  stage: test
  tags:
  - node
  before_script:
  - cd todo-app/
  - yarn config set cache-folder .yarn
  - yarn install
  script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install google-chrome-stable -y

  - yarn test:headless

cypress-install:
  image: cypress/base:10
  stage: build
  before_script:
  - cd e2e/
  script:
  - npm ci
  - $(npm bin)/cypress verify

# two jobs that run after "install" job finishes
# NPM dependencies and Cypress binary should be already installed
cypress-e2e:
  image: cypress/base:10
  stage: test
  script:
  - $(npm bin)/cypress run
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos

cypress-e2e-chrome:
  image: cypress/browsers:chrome67
  stage: test
  before_script:
  - cd e2e/
  script:
  - $(npm bin)/cypress run --browser chrome
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
