image: node:9.4.0

cache:
  paths:
  - node_modules/
  - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

Build:
  stage: build
  tags:
  - node
  before_script:
  - cd angular-testing-recipes/
  - yarn config set cache-folder .yarn
  - yarn install
  script:
  - yarn build

Test:
  stage: test
  tags:
  - node
  before_script:
  - cd angular-testing-recipes/
  - yarn config set cache-folder .yarn
  - yarn install
  script:

  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install google-chrome-stable -y

  - yarn test